INSERT INTO techniques (slug, category, title_en, title_ru, description_en, description_ru, steps_en, steps_ru, duration_seconds, difficulty, safety_notes_en, safety_notes_ru) VALUES
('5-4-3-2-1-grounding', 'grounding', '5-4-3-2-1 Grounding', 'Заземление 5-4-3-2-1', 'Use your senses to anchor yourself in the present moment.', 'Используйте свои чувства, чтобы закрепиться в текущем моменте.', '["Notice 5 things you can see", "Notice 4 things you can touch", "Notice 3 things you can hear", "Notice 2 things you can smell", "Notice 1 thing you can taste"]', '["Заметьте 5 вещей, которые вы видите", "Заметьте 4 вещи, которые можете потрогать", "Заметьте 3 вещи, которые слышите", "Заметьте 2 вещи, которые чувствуете по запаху", "Заметьте 1 вещь, которую чувствуете на вкус"]', 180, 'easy', 'If this causes distress, stop and try a different technique.', 'Если это вызывает стресс, прекратите и попробуйте другую технику.'),
('space-orientation', 'grounding', 'Space Orientation', 'Ориентация в пространстве', 'Ground yourself by identifying where and when you are.', 'Закрепитесь, определив где вы находитесь и какое сейчас время.', '["Name where you are right now", "State today''s date", "Identify 3 objects around you", "Notice your body position"]', '["Назовите, где вы находитесь прямо сейчас", "Назовите сегодняшнюю дату", "Определите 3 предмета вокруг вас", "Заметьте положение вашего тела"]', 120, 'easy', NULL, NULL),
('gentle-breathing', 'breathing', 'Gentle Breathing', 'Мягкое дыхание', 'Focus on your natural breath without trying to change it.', 'Сосредоточьтесь на своем естественном дыхании, не пытаясь его изменить.', '["Find a comfortable position", "Close your eyes or soften your gaze", "Notice the rhythm of your breath", "Observe without changing anything"]', '["Найдите удобное положение", "Закройте глаза или расслабьте взгляд", "Заметьте ритм своего дыхания", "Наблюдайте, не меняя ничего"]', 180, 'easy', NULL, NULL),
('facts-vs-assumptions', 'cognitive', 'Facts vs Assumptions', 'Факты и предположения', 'Separate what actually happened from the stories your mind creates.', 'Отделите то, что произошло на самом деле, от историй, которые создает ваш ум.', '["Write down what objectively happened", "List the assumptions you made", "Ask: What evidence supports this?", "Ask: What evidence contradicts this?"]', '["Запишите, что объективно произошло", "Перечислите сделанные вами предположения", "Спросите: Какие доказательства это подтверждают?", "Спросите: Какие доказательства это опровергают?"]', 300, 'easy', NULL, NULL),
('catastrophic-thought-check', 'cognitive', 'Catastrophic Thought Check', 'Проверка катастрофических мыслей', 'Challenge catastrophic thinking by exploring different scenarios.', 'Оспорьте катастрофическое мышление, исследуя различные сценарии.', '["What is the worst that could happen?", "What is the most likely outcome?", "What is the best that could happen?", "Which scenario is most probable?"]', '["Какой худший сценарий возможен?", "Какой наиболее вероятный исход?", "Какой лучший сценарий возможен?", "Какой сценарий наиболее вероятен?"]', 300, 'medium', 'If you feel overwhelmed, stop and seek support.', 'Если вы чувствуете подавленность, остановитесь и обратитесь за поддержкой.'),
('circle-of-control', 'behavioral', 'Circle of Control', 'Круг контроля', 'Identify what is within your power to influence.', 'Определите, что находится в вашей власти.', '["Draw a large circle on paper", "Inside: list things you can control", "Outside: list things you cannot control", "Focus your energy inward"]', '["Нарисуйте большой круг на бумаге", "Внутри: перечислите вещи, которые вы можете контролировать", "Снаружи: перечислите вещи, которые вы не можете контролировать", "Сосредоточьте энергию внутри"]', 300, 'easy', NULL, NULL),
('one-small-step', 'behavioral', 'One Small Step', 'Один маленький шаг', 'Overcome inertia by identifying one tiny action you can take.', 'Преодолейте инерцию, определив одно маленькое действие, которое вы можете выполнить.', '["Identify one tiny thing you can do right now", "Make it specific and actionable", "Commit to doing just that one thing", "Celebrate the completion"]', '["Определите одну маленькую вещь, которую можете сделать сейчас", "Сделайте это конкретным и выполнимым", "Обещайте сделать только это одно", "Отметьте выполнение"]', 180, 'easy', NULL, NULL),
('self-compassion-break', 'compassion', 'Self-Compassion Break', 'Пауза для самосострадания', 'Treat yourself with the kindness you would offer a friend.', 'Отнеситесь к себе с добротой, которую вы бы предложили другу.', '["Place your hand over your heart", "Acknowledge: This is a moment of suffering", "Say: May I be kind to myself", "Offer yourself words of comfort"]', '["Положите руку на сердце", "Признайте: Это момент страдания", "Скажите: Пусть я буду добр к себе", "Предложите себе слова утешения"]', 180, 'easy', NULL, NULL);
